=== ian-rosenberg/ForeverYourDevil-Public/Assets/VN_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

  <!--
    Conversation Hierarchy
    Title of xml script MUST be the same name as the level/scene name
      <game>
        <conversation id="_____">
          <character name="_____" (optional)>
            <line sprite1="____" (optional) sprite2="____" (optional)>________________</line>
            <option>
              <choice id="____">________</choice>
            </option>
          </character>
        </conversation>
      </game> //END
  -->
  
  <!--Root node-->
  <xs:element name = "game">
    <xs:complexType>
      <xs:sequence>
        <xs:element name = "conversation" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name = "character" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name = "line">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="sprite1" type="xs:string" use="optional"/>
                            <xs:attribute name="sprite2" type="xs:string" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name = "options">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name = "choice" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:choice>
                  <xs:attribute name="name" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ian-rosenberg/ForeverYourDevil-Public/Assets/_My Assets/Resources/AnimationTest.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Schema must be removed before gameplay
<game
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com/xml VN_Schema.xsd">
  -->
<game>
  
  <!--Testing Animations-->  
  <conversation id="Anim_Test">
    <character name="Penny">
      <line AC_L="Test_AC" AC_R="Test_AC" emotion_L="Idle" emotion_R="Idle">This is the animation test.</line>
      <line emotion_L="Happy">Happy.</line>
      <line>Still happy.</line>
      <line emotion_L="Mad">Mad.</line>
    </character>
    <character name="Beautiful Friend">
      <line AC_L="Default_AC" AC_R="Test_AC" emotion_R="Sad">Sad. Oh, look, tan pill.</line>
      <line>Still sad.</line>
      <line emotion_R="Surprised">Surprised.</line>
    </character> 
  </conversation>

  <conversation id="Anim_Test2">
    <character name="Cinnamon Roll">
        <line AC_L="Test_AC" emotion_L="Surprised">Who are you?</line>
    </character>
    <character name="???">
        <line>wgfehrjgtkfhdwqwefgrhj.</line>
    </character>
    <character name="Cinnabon">
        <line emotion_L="Idle">Oh.</line>
    </character>
    <character name="wgfehrjgtkfhdwqwefgrhj">
      <line>wefjkgrdfglhgjafhdggjdgkldjhaefghgsa.</line>
    </character>
    <character name="Cinnamon Toast Crunch">
      <line emotion_L="Default">wefjkgrdfglhgjafhdggjdgkldjhaefghgsa.</line>
      <line emotion_R="does not exist">My emotions do not exist.</line>  
    </character>
  </conversation>

  <conversation id="Anim_Test3">
    <character name="Void">
      <line AC_L="Test_AC">I am the void.</line>
    </character>      
  </conversation>  
  
  <!--Testing Official Animations-->
  <conversation id="Official_Test">
    <character name="Penny">
      <line AC_L="Penny_AC" emotion_L="Talking" AC_R="Penny_AC" emotion_R="Idle">'Twas brillig, and the slithy toves</line>
      <line>Did gyre and gimble in the wabe:</line>
      <line>All mimsy were the borogoves,</line>
      <line>And the mome raths outgrabe.</line>
      <line emotion_L="AmazedTalk" emotion_R="Confused">"Beware the Jabberwock, my son!</line>
      <line>The jaws that bite, the claws that catch!</line>
      <line>Beware the Jubjub bird, and shun</line>
      <line>The frumious Bandersnatch!"</line>
    </character>
    <character name="Also Penny">
      <line emotion_L="Amazed" emotion_R="ConfusedTalk">He took his vorpal sword in hand;</line>
      <line>Long time the manxome foe he sought--</line>
      <line>So rested he by the Tumtum tree</line>
      <line>And stood awhile in thought.</line>
      <line emotion_L="Idle" emotion_R="Talking">And, as in uffish thought he stood,</line>
      <line>The Jabberwock, with eyes of flame,</line>
      <line>Came whiffling through the tulgey wood,</line>
      <line>And burbled as it came!</line>
    </character>
    <character name="Penny">
      <line emotion_L="SadTalk" emotion_R="Sad">One, two! One, two! And through and through</line>
      <line>The vorpal blade went snicker-snack!</line>
      <line>He left it dead, and with its head</line>
      <line>He went galumphing back.</line>
      <line emotion_L="AmazedTalk">"And hast thou slain the Jabberwock?</line>
      <line>Come to my arms, my beamish boy!</line>
      <line>O frabjous day! Callooh! Callay!"</line>
      <line emotion_L="SadTalk">He chortled in his joy.</line>
    </character>
    <character name="Also Penny">
      <line emotion_L="Idle" emotion_R="Talking">'Twas brillig, and the slithy toves</line>
      <line>Did gyre and gimble in the wabe:</line>
      <line>All mimsy were the borogoves,</line>
      <line>And the mome raths outgrabe.</line>
    </character>
  </conversation>
    
  <!--Testing Official Animations with Voice Over-->
  <conversation id="Genovese_Threat" voice="{eb4e9ad8-c6ac-414f-8d5e-c3d012ca6ae6}">
    <character name="Genovese">
        <line AC_L="Default_AC" AC_R="Penny_AC" emotion_R="Talking">Hehehehehehehe.....</line>
        <line>My, you've been a naughty girl..... >:3</line>
        <line>I was originally planning on letting you leave with only minor bodily harm, but...</line>
        <line>After the way you just pissed me off by rummaging through my things...</line>
        <line>I think I'd rather enjoy seeing someone clean what's left of you out of my carpet.</line>
        <line>Shall we begin?</line>
        <options>
          <choice id="No">No</choice>
          <choice id="Genovese_Threat">Restart?</choice>
        </options>
    </character>
  </conversation>

  <conversation id="No">
    <character name="Penny">
      <line AC_L="Default_AC" AC_R="Penny_AC" emotion_R="Idle">No, u.</line>
    </character>
  </conversation>

</game>

=== ian-rosenberg/ForeverYourDevil-Public/Assets/Resources/MovementTest.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Schema must be removed before gameplay
<game
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com/xml VN_Schema.xsd">
  -->
<game>
  <!--Testing sprites-->
  <conversation id="3">
    <character name="Chibi">
      <line sprite1="01" sprite2="mermaid">Alright, Adult me, be honest.</line>
    </character>
    <character name="Adult">
      <line>What's up, Chibi me? Honest about what?</line>
    </character>
    <character name="Chibi">
      <line>Who do the people really want to see here?</line>
      <options>
        <choice id="Tan Pill">Tan Pill!</choice>
        <choice id="Mermaids">Mermaids!</choice>
        <choice id="No one">Neither!</choice>
      </options>
    </character>
  </conversation>

  <conversation id="Tan Pill">
    <character name="Tan Pill">
      <line sprite1="Player" sprite2="NPC">Aha!!! Tan Pill returns!!!!</line>
      <line>I'm glad to be back in the flesh!</line>
      <line>Guess that's settled!</line>
    </character>
  </conversation>

  <conversation id="Mermaids">
    <character name="Chibi">
      <line sprite1="01" sprite2="mermaid">Oh thank the stars...</line>
      <line>I'm really glad that the player picked us.</line>
    </character>
    <character name="Adult">
      <line>Now doesn't that feel better?</line>
      <line>Hope that helps with your insecurity!</line>
    </character>
    <character name="Chibi">
      <line>...</line>
      <line>didYouReallyHaveToBeThatBluntAboutIt??? 0_0</line>
    </character>
  </conversation>

  <conversation id="No one">
    <character name="Chibi">
      <line sprite1="01" sprite2="mermaid">...</line>
      <line>Guess that's settled...</line>
      <line>Ughhhhh...</line>
    </character>
  </conversation>

  <conversation id="Penny Test">
    <character name="Penny">
      <line sprite1="Penny_Happy" sprite2="Player">Is that who I think it is???</line>
      <line sprite1="Penny_Wow" sprite2="Player">GASPPPPP. IT IS!!!!</line>
      <line>IT'S TAN PILL, THE INSIDE JOKE!</line>
    </character>
    <character name="Tan Pill">
      <line>In the flesh! Or uh, in the Hypromellose Gelletin Alternative...</line>
    </character>
  </conversation>

</game>

=== ian-rosenberg/ForeverYourDevil-Public/Assets/_My Assets/Resources/SceneMerge.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Schema must be removed before gameplay
<game
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com/xml VN_Schema.xsd">
  -->
<game>
  <!--Testing animated sprites and voice lines-->
  <conversation id="Penny Test" = >
    <character name="Penny">
      <line AC_L="Penny_AC" emotion_L="Talking" AC_R="Default_AC">Yoooooo, Tan Pill!</line>
    </character>
    <character name="Tan Pill">
      <line emotion_L="Idle">That's my hastily assigned identification string! Don't wear it out!</line>
    </character>
    <character name="Penny">
      <line emotion_L="ConfusedTalk">What?</line>
    </character>
    <character name="Tan Pill">
      <line emotion_L="Confused">What?</line>
    </character>
    <character name="Penny">
      <line emotion_L="Talking">Uhh, anyhow! How goes there? You excited for this update vid coming out?</line>
    </character>
    <character name="Tan Pill">
      <line emotion_L="Idle">You betcha I am, poster girl, I MEAN, Penny!</line>
      <line>In fact, I'd say I'm so excited...</line>
      <line>*slidessssss out*</line>
    </character>
    <character name ="PENNY! :3">
      <line emotion_L="Idle" AC_R="Penny_AC" emotion_R="AmazedTalk">...THAT I COULD TRANSFORRRRRRRRRRRRRRM!!!!!!!!</line>
    </character>
    <character name="Penny">
      <line emotion_L="AmazedTalk" emotion_R="Amazed">WOAHHHHHHHHHHHHHH!!!!!</line>
    </character>
    <character name="PENNY! :3">
      <line emotion_L="Amazed" emotion_R="AmazedTalk">HAHAHAHA!!!!! I AM YOU NOW!</line>
      <line emotion_L="Amazed" emotion_R="Talking">What do you think, original, but slightly less handsome Penny?!!!</line>
      <options>
        <choice id="Cool">THAT'S SO COOL!!!!</choice>
        <choice id="What">What the actual hell???</choice>
      </options>
    </character>
  </conversation>

  <conversation id="What">
    <character name="Penny">
      <line emotion_L="AmazedTalk" emotion_R="Idle">What the actual hell?!?!?!?!!</line>
      <line>It's like looking in a mirror! Except... with DEPTH.</line>
    </character>
    <character name="PENNY! :3">
      <line emotion_L="Amazed" emotion_R="Talking">It's so flippin cool, right?!!</line>
      <line emotion_L="Idle">It's a shame that I can only sustain this form for one mor--</line>
    </character>
    <character name="Tan Pill">
      <line emotion_L="Idle" AC_R="Default_AC">...</line>
      <line emotion_L="Confused">Crap...</line>
    </character>
  </conversation>

  <conversation id="Cool">
    <character name="Penny">
      <line emotion_L="AmazedTalk" emotion_R="Idle">THAT'S SO COOOOOOOOOOOOOOOL!!!!</line>
      <line emotion_L="AmazedTalk" emotion_R="Idle">You even got the detail in my hair all flipped and stuff!</line>
    </character>
    <character name="PENNY! :3">
      <line emotion_L="Amazed" emotion_R="AmazedTalk">I'm proud of all the detail, heck yeah!</line>
    </character>
    <character name="Penny">
      <line emotion_L="ConfusedTalk" emotion_R="Idle">Though I will say, the artist who drew you... me?? We?? Yeah we.</line>
      <line emotion_L="SadTalk">Whoever drew us should have probably made it so that this form lasted a little...</line>
    </character>
    <character name="Penny">
      <line AC_L="Default_AC" emotion_R="Idle">...</line>
      <line >AHHHHHHHHHHHHHHHHHHHHHHHHHHHH!</line>
    </character>
    <character name="PENNY! :3">
      <line emotion_R="AmazedTalk">AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH!</line>
    </character>
  </conversation>

</game>

=== ian-rosenberg/ForeverYourDevil-Public/Assets/_My Assets/Resources/DoorsTest.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Schema must be removed before gameplay
<game
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com/xml VN_Schema.xsd">
  -->
<game>
  <!--Testing animated sprites and voice lines-->
  <conversation id="Penny Test">
    <character name="Penny">
      <line sprite1="Penny_Normal" sprite2="Player">Yoooooo, Tan Pill!</line>
    </character>
    <character name="Tan Pill">
      <line>That's my hastily assigned identification string! Don't wear it out!</line>
    </character>
    <character name="Penny">
      <line sprite1="Penny_Sweat" sprite2="Player">What?</line>
    </character>
    <character name="Tan Pill">
      <line>What?</line>
    </character>
    <character name="Penny">
      <line sprite1="Penny_Normal" sprite2="Player">Uhh, anyhow! How goes there? You excited for this update vid coming out?</line>
    </character>
    <character name="Tan Pill">
      <line>You betcha I am, poster girl, I MEAN, Penny!</line>
      <line>In fact, I'd say I'm so excited...</line>
      <line>*slidessssss out*</line>
    </character>
    <character name ="PENNY! :3">
      <line sprite1="Penny_Normal" sprite2="Penny_Wow">...THAT I COULD TRANSFORRRRRRRRRRRRRRM!!!!!!!!</line>
    </character>
    <character name="Penny">
      <line sprite1="Penny_Wow" sprite2="Penny_Wow">WOAHHHHHHHHHHHHHH!!!!!</line>
    </character>
    <character name="PENNY! :3">
      <line>HAHAHAHA!!!!! I AM YOU NOW!</line>
      <line sprite1="Penny_Wow" sprite2="Penny_Normal">What do you think, original, but slightly less handsome Penny?!!!</line>
      <options>
        <choice id="Cool">THAT'S SO COOL!!!!</choice>
        <choice id="What">What the actual hell???</choice>
      </options>
    </character>
  </conversation>

  <conversation id="What">
    <character name="Penny">
      <line sprite1="Penny_Wow" sprite2="Penny_Normal">What the actual hell?!?!?!?!!</line>
      <line sprite1="Penny_Wow" sprite2="Penny_Normal">It's like looking in a mirror! Except... with DEPTH.</line>
    </character>
    <character name="PENNY! :3">
      <line sprite1="Penny_Normal" sprite2="Penny_Normal">It's so flippin cool, right?!!</line>
      <line sprite1="Penny_Normal" sprite2="Penny_Normal">It's a shame that I can only sustain this form for one mor--</line>
    </character>
    <character name="Tan Pill">
      <line sprite1="Penny_Normal" sprite2="Player">...</line>
      <line>Crap...</line>
    </character>
  </conversation>

  <conversation id="Cool">
    <character name="Penny">
      <line sprite1="Penny_Wow" sprite2="Penny_Normal">THAT'S SO COOOOOOOOOOOOOOOL!!!!</line>
      <line sprite1="Penny_Wow" sprite2="Penny_Normal">You even got the detail in my hair all flipped and stuff!</line>
    </character>
    <character name="PENNY! :3">
      <line sprite1="Penny_Wow" sprite2="Penny_Normal">I'm proud of all the detail, heck yeah!</line>
    </character>
    <character name="Penny">
      <line sprite1="Penny_Sweat" sprite2="Penny_Normal">Though I will say, the artist who drew you... me?? We?? Yeah we.</line>
      <line>Whoever drew us should have probably made it so that this form lasted a little...</line>
    </character>
    <character name="Penny">
      <line sprite1="Player" sprite2="Penny_Normal">...</line>
      <line>AHHHHHHHHHHHHHHHHHHHHHHHHHHHH!</line>
    </character>
    <character name="PENNY! :3">
      <line sprite1="Player" sprite2="Penny_Wow">AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH!</line>
    </character>
  </conversation>

</game>
